version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - CLIENT_URL=http://localhost:3000
      - SESSION_SECRET=your-super-secret-key-for-docker
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
    environment:
      # This tells the proxy where to send API requests.
      # 'backend' is the service name from this file.
      - REACT_APP_API_URL=http://backend:3001
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules