version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      # Maps port 5000 of the host to port 5000 in the container
      - "5000:5000"
    volumes:
      # Persists the SQLite database file on your host machine
      - ./server/data:/app/server/data
    env_file:
      # Loads environment variables from your .env file
      - ./.env
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      # Maps port 3000 of the host to port 80 in the container
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
