version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      # For development, allow requests from the local client dev server
      - CLIENT_URL=http://localhost:3000
      - SESSION_SECRET=your-super-secret-key-for-docker
    volumes:
      # Mount local source code for hot-reloading.
      # Ensure file sharing is enabled in Docker Desktop settings.
      - ./server:/app
      - /app/node_modules

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
      # In development, we only need the 'builder' stage to install dependencies
      target: builder
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      # Mount local source code for hot-reloading.
      - ./client:/app
      - /app/node_modules
    # Override the production command to start the dev server
    command: npm start